add check to upgrade to warn for not supported php version; disable geoip for php <5.4
mailwatch/1.2.0 pull request #1075
Opened 2018-06-04 15:08 UTC by Skywalker-11

#1073

2018-06-05 07:21 UTC, stefaweb commented on mailscanner/languages/fr.php
> +    'geoipnotsupported04' => 'GeoIP not supported',
'geoipnotsupported04' => 'GeoIP non pris en charge',

2018-06-13 08:37 UTC, endelwar requested changes

2018-06-13 08:37 UTC, endelwar commented on upgrade.php
> +    echo color(' WARNING: PHP version < 5.4 not fully supported (GeoLite2 not working)', 'red'). PHP_EOL;
I would issue a yellow warning instead of a red error for this

2018-06-20 01:50 UTC, endelwar approved these changes

2018-06-20 01:50 UTC, merged

2018-06-20 07:42 UTC, Skywalker-11 commented
@endelwar can you also take a look at the PRs of the doc?

2018-06-20 08:10 UTC, endelwar commented
https://github.com/mailwatch/mailwatch-docs/pull/36 merged