PT_BR Translations
mailwatch/1.2.0 pull request #1103
Opened 2018-08-06 16:05 UTC by rafaelbsd

Updates to mailscanner/langagues/pt_br.php

2018-08-06 17:39 UTC, endelwar commented on mailscanner/languages/pt_br.php
> +    'mailscanner03' => 'Mailscanner:',
Please leave MailScanner name as is

2018-08-06 17:44 UTC, endelwar requested changes

2018-08-06 17:44 UTC, endelwar commented on mailscanner/languages/pt_br.php
> +    'auditlog0412' => 'Usuário %s excluído	',
Are these spaces necessary?

2018-08-06 17:58 UTC, rafaelbsd commented on mailscanner/languages/pt_br.php
> +    'auditlog0412' => 'Usuário %s excluído	',
Hi... no, they are not. I'll fix it.

2018-08-06 18:00 UTC, rafaelbsd commented
Already fixed those unecessary spaces.

2018-08-06 18:03 UTC, rafaelbsd commented on mailscanner/languages/pt_br.php
> +    'mailscanner03' => 'Mailscanner:',
OK. Fixed it.

2018-08-06 18:03 UTC, rafaelbsd commented on mailscanner/languages/pt_br.php
> +    'auditlog0412' => 'Usuário %s excluído	',
Fixed it.

2018-08-07 12:22 UTC, rafaelbsd reviewed
Fixed MailScanner name and unnecessary spaces.

2018-08-07 16:30 UTC, rafaelbsd reviewed
MailScanner name

2018-08-07 17:20 UTC, endelwar approved these changes

2018-08-07 17:20 UTC, merged